services:
  api:
    image: hashibutogarasu/karasu-lab-admin-api:nightly
    restart: unless-stopped
    ports:
      - "8084:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/default.yml:/app/configs/default.yml:ro
    environment:
      - NODE_ENV=production
